#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-adv_recovery
/var/log/asterisk/adv_recovery_*.log{
	size 50M
	missingok
	rotate 5
	notifempty
	sharedscripts
	dateext
	create 0640 asterisk asterisk
	su asterisk asterisk
	postrotate
		/usr/sbin/fwconsole pm2 --reload-logs -q
	endscript
}
EOF
