#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-iub24
/var/log/asterisk/iub24-proxy_err.log
/var/log/asterisk/iub24-proxy_out.log{
	daily
	missingok
	notifempty
	dateext
	dateformat -%Y%m%d
	rotate 10
  create 0640 asterisk asterisk
  su asterisk asterisk
}
EOF
