#!/bin/bash

cat <<- EOF > /etc/logrotate.d/freepbx-dpma
/var/log/asterisk/dpma{
	size 50M
	missingok
	rotate 5
	notifempty
	sharedscripts
	dateext
	create 0640 asterisk asterisk
	su asterisk asterisk
}
EOF
